#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Usage: $0 <test-set-file>" >&2 # Send this to stderr
fi

for file_stem in $(cat "$1"); do
    if [[ -f "${file_stem}.desc" ]]; then # Although the curly-braces aren't necessary here I just maintain them for neatness. We use -f for regular files, and -e for anything, but we just want to know the regular file effectively.
        cat "${file_stem}.desc"
    else
        echo "stem: No test description"
    fi
done