#!/bin/bash

if [[ -z "$2" ]]; then
    echo "Usage: $0 <wc-set-file>" >&2 # Send this to stderr
fi

file_stems=($(cat "$2"))
# Reminder: $() runs a command and ${} captures an output
# Took some of this code I wrote from q2
for file_stem in "${file_stems[@]}"; do
    temp="$(mktemp)"
    if [[ -f "${file_stem}.in" ]]; then # Although the curly-braces aren't necessary here I just maintain them for neatness. We use -f for regular files, and -e for anything, but we just want to know the regular file effectively.
        $1 < "${file_stem}.in" > "${temp}" 2>&1 # input to wc then output to a output.txt file, capture stderr and stdout
        # Now produce an exit code and logically test
        if diff -q "${temp}" "${file_stem}.out"; then
            echo "Test ${file_stem} passed"
        else
            echo "Test ${file_stem} failed"
            echo "Expected output:"
            cat "${file_stem}.out"
            echo "Actual output:"
            cat "${temp}"
        fi
    else
        echo "stem: No wc-test description"
    fi
    
    # remove the temp-file
    rm "${temp}"
done