#!/bin/bash

command=$(cat "$1" )


if [[ -z "$2" ]]; then
    echo "Usage: $0 <wc-set-file>" >&2 # Send this to stderr
fi

file_stems=($(cat "$2"))

# Took some of this code I wrote from q2
for file_stem in "${file_stems[@]}"; do
    temp=${mktemp}
    if [[ -f "${file_stem}.in" ]]; then # Although the curly-braces aren't necessary here I just maintain them for neatness. We use -f for regular files, and -e for anything, but we just want to know the regular file effectively.
        wc < "${file_stem}.in" > output.txt # input to wc then output to a output.txt file
        if 
    else
        echo "stem: No wc-test description"
    fi
done